# Solely for timing
from timeit import default_timer as timer
from llama2local import qa_bot, chatbot_response, non_qa_bot

start = timer()
chatbot = qa_bot()
end = timer()
print(end - start)
start = timer()
print(chatbot_response("What is my Armor Class?", chatbot))
end = timer()
print(end - start)
start = timer()
chatbot = non_qa_bot()
end = timer()
print(end - start)
start = timer()
print(chatbot.predict(user_input="What is dungeons and dragons?"))
end = timer()
print(end - start)
start = timer()
print(chatbot.predict(user_input="How do I play dungeons and dragons?"))
end = timer()
print(end - start)
start = timer()
print(chatbot.predict(user_input="What is a dwarf in dungeons and dragons?"))
end = timer()
print(end - start)
start = timer()
print(chatbot.predict(user_input="What was my first question?"))
end = timer()
print(end - start)
